name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: stable

    - name: Create Neovim config directories
      run: |
        mkdir -p ~/.local/share/nvim/lazy
        mkdir -p ~/.config/nvim/lua

    - name: Install plenary.nvim
      run: |
        git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/lazy/plenary.nvim

    - name: Run Tests
      run: |
        ./bin/run-tests